### ISSUE TITLE
Question about the performance of the code and performance in the vedio.

### ISSUE THREAD

**Issue by Gaochao-hit** [ChaoqinRobotics/LINS---LiDAR-inertial-SLAM#19]
Thank you for your great work. I have a quetion whether the code you release is the same as that in the vedio. The performance of your algorithm in the vedio is really excellent.

**Comment by ChaoqinRobotics** [comment]
It is a simplified version of the original code, but the performance is bascially the same. Please feel free to test it on your dataset. One thing you need to notice is that since the IMU-lidar extrinsic parameters are not considered in this version of LINS, it is suggested that the IMU should be placed as close as possible to the Lidar.

**Comment by Gaochao-hit** [comment]
> It is a simplified version of the original code, but the performance is bascially the same. Please feel free to test it on your dataset. One thing you need to notice is that since the IMU-lidar extrinsic parameters are not considered in this version of LINS, it is suggested that the IMU should be placed as close as possible to the Lidar.

Thank you for your reply.
