### ISSUE TITLE
Ft matrix

### ISSUE THREAD

**Issue by G3tupup** [ChaoqinRobotics/LINS---LiDAR-inertial-SLAM#4]
In your code in KalmanFilter.hpp line 159: 
Ft.block<3, 3>(GlobalState::att_, GlobalState::att_) =
          skew(gyr - state_tmp.bw_);
But according to your paper and code in LIO-Mapping, this block is  "-skew(gyr - state_tmp.bw_)", Is this a bug?

**Comment by ChaoqinRobotics** [comment]
Thanks you for pointing it out! It's a typo in the paper. Please follow the code. If you are interested in the derivation, you can refer to "Quaternion kinematics for the error-state Kalman lter", where you can find similar formulas (but the definition of gravity is a littble bit different, which leads to different values in the gravity block in Ft). : )

**Comment by ChaoqinRobotics** [comment]
It is a bug. I have revised the code and test it in all datasets. It seems like it does not has any influences to the result. I think it is because this term is so small compared to other blocks that its effect is not obvious. Anyways, thanks for point it out : )

Also, please notice that there is a new typo in my paper abuot Ft.  The derivative of the velocity with respect to the gravity should be a 3x3 identity matrix, while the derivative of the attitude with respect to the gravity should be leaved blank, just like what the code does--Ft.block<3, 3>(GlobalState::vel_, GlobalState::gra_) = M3D::Identity();

**Comment by G3tupup** [comment]
> It is a bug. I have revised the code and test it in all datasets. It seems like it does not has any influences to the result. I think it is because this term is so small compared to other blocks that its effect is not obvious. Anyways, thanks for point it out : )
> 
> Also, please notice that there is a new typo in my paper abuot Ft. The derivative of the velocity with respect to the gravity should be a 3x3 identity matrix, while the derivative of the attitude with respect to the gravity should be leaved blank, just like what the code does--Ft.block<3, 3>(GlobalState::vel_, GlobalState::gra_) = M3D::Identity();

Thank you! It seems to be the same as typos in Joan Sola's paper.

**Comment by narutojxl** [comment]
It seems that coefficient **A** of equ 375 in joan sola is right.
![2020-05-26 15-51-40屏幕截图](https://user-images.githubusercontent.com/6205343/82874649-d65c2680-9f68-11ea-9c3f-80a81702a651.png)
BTW, in lins paper equ 10, 11, the rotation matrix's superscript should be none or $b_k$, is it a typo?
![1](https://user-images.githubusercontent.com/6205343/82875787-6ea6db00-9f6a-11ea-9786-95165450bc89.png)
